### ISSUE TITLE
Search problem when not in server mode

### ISSUE THREAD

**Issue by te-deum** [bhaveshpatel200/vue3-datatable#12]
Hi,

While upgrading my npm modules, I have a strange problem. When I am searching, the searches inside the datatable are delayed.
I finally found why : In file _/src/components/custom-table.vue_ around lines 730-736
You first watch _search_ props changes and call _changeSearch_ function before the watch _search_ props that change the _currentSearch_ const. You may invert these watch to not have a delay between search props and searched value.
Change these lines :
```
watch(() => props.search, changeSearch);
watch(
    () => props.search,
    () => {
        currentSearch.value = props.search;
    }
);
```
By these lines :
```
watch(
    () => props.search,
    () => {
        currentSearch.value = props.search;
    }
);
watch(() => props.search, changeSearch);
```

**Comment by bhaveshpatel200** [comment]
HI,

Can you please reproduce this in one of my demos, if yes then please give me all the steps to reproduce first and then i will think about that.

**Comment by te-deum** [comment]
Your demos are in server mode. So I can't reproduce the problem.

Everything was working fine since I update local npm packages (It update Vue from 3.3.4 to 3.3.7).
I reproduce locally with both datatable version (1.1.1 and 1.1.2).

It seems logic that both watch orders are not coherent since _currentSearch_ is used in _filterRow_. If _currentSearch_ is not updated by watcher before calling _filterRow_ then _filterRow_ will search with an outdated _currentSearch_ value.

**Comment by bhaveshpatel200** [comment]
Actually we have not changed anything regarding search, so its very strange.

Ok, can you please give me proper steps for reproduce that scenarios, so i can check easily and update if needed.

**Comment by te-deum** [comment]
Here is a very simple example that reproduce the problem.
Hope you will have the same result...
[dt-test.zip](https://github.com/bhaveshpatel200/vue3-datatable/files/13238450/dt-test.zip)

**Comment by bhaveshpatel200** [comment]
Ok, will check and let you know.

**Comment by te-deum** [comment]
Re,

I just try to merge both watch into one and it work. It might be better for "optimization".
```
watch(
    () => props.search,
    () => {
        currentSearch.value = props.search;
        changeSearch();
    }
);
```

**Comment by bhaveshpatel200** [comment]
Hi,

Ok, i will check and update.

But It's very strange to not working your demo and already working fine on our vue3 template.
you can check from below link.
https://vristo-vue.vercel.app/datatables/order-sorting

**Comment by te-deum** [comment]
Yes, I agree that it's strange. Everything was working fine since I update Vue package to 3.3.7.

FYI : We are using Vristo here in our project and we love it 👍
I upgrade every package to the latest version without problem (I just have to replace _@intlify/vite-plugin-vue-i18n_ _intlify/unplugin-vue-i18n_ and remove _import '@fullcalendar/core/vdom';_ in calendar with the latest version of _Full Calendar_)

**Comment by bhaveshpatel200** [comment]
Yes, seems search not working properly with latest vue version.

Have you test this solution proper for both client and server side renderings?
**watch(
    () => props.search,
    () => {
        currentSearch.value = props.search;
        changeSearch();
    }
);**

**Comment by te-deum** [comment]
No, but it should work cause it's similar to both watch in only one call.

**Comment by bhaveshpatel200** [comment]
Yes, I know. i will check and update soon.

Thanks

**Comment by bhaveshpatel200** [comment]
Hi te-deum, 

Resolved above issue and updated package.
