### ISSUE TITLE
Table don't refresh when add new row in push array 

### ISSUE THREAD

**Issue by alesb2010** [bhaveshpatel200/vue3-datatable#14]
We make fresh install and a lot of tests with Vue 3.3.4 and 3.3.7 versions.
We try the versions from vue3-datatable 1.0.1 to the 1.1.3
This tests using only a clean install, and one using Nuxt 3.8 and 3.6.2.
We made server-side and client-side, with no sucess.
We don't get any issue in console from Chrome or console server side.
We inspect the Vue array, and all data is updated, but no in the DOM.
All the test we made, when we push a data to the const with ref, the data don't update on the table in DOM.

**Comment by bhaveshpatel200** [comment]
Hi Alexandre Brandao,
Can you please provide sample demo code for that, so we can reproduce that easily and solve if any issue.

**Comment by alesb2010** [comment]
Hello Mr. Bhavesh Patel,
Yesterday I have some time and restart all my folders projects and clear all my caches in instances. 
Then all the issue was solved. 
I have a impression that is my instance cache that block some functions to REF components.. etc..
Thanks a lot for your attention and help.
Have a nice day!

**Comment by bhaveshpatel200** [comment]
Great, Thanks.
