### ISSUE TITLE
Rendering data from API

### ISSUE THREAD

**Issue by SathishNaqel** [bhaveshpatel200/vue3-datatable#2]
Hi Bhavesh,
Can you please provide a sample for how to load data from API and render inside datatable in Vue3 Compostion API.

Thanks,
sathish

**Comment by ohso-tokyo** [comment]
Hi Satish,

You just need to get data from API using **Axios** or any other library and need to pass in all data in **rows** which is already in our examples.

You can find all the examples with the source code from the below link:
[https://vue3-datatable-document.vercel.app/](https://vue3-datatable-document.vercel.app)

**Comment by bhaveshpatel200** [comment]
Hi Satish,

You just need to get data from API using **Axios** or any other library and need to pass in all data in **rows** which is already in our examples.

You can find all the examples with the source code from the below link:
[https://vue3-datatable-document.vercel.app/](https://vue3-datatable-document.vercel.app)

**Comment by bhaveshpatel200** [comment]
Hi @SathishNaqel,
Its good news!.
Now our datatable supports server-side rendering and its live in latest release version 1.1.0.

I have also updated all the demos in server side rendering. so you can find the code from that.
