### ISSUE TITLE
Rows don't render when :show-page-size="false"

### ISSUE THREAD

**Issue by tekord** [bhaveshpatel200/vue3-datatable#20]
Hi! I have the following code:

```
      <vue3-datatable
        :rows="rows"
        :columns="columns"
        :show-page-size="false"
        :pagination="false"
      />
```

`rows` contains an array of items loaded from server (6 items). Rows don't row when I use ` :show-page-size="false"`, no DOM elements in the table's body.

UPD. Weird, sometimes it doesn't render when pagination is off.

**Comment by bhaveshpatel200** [comment]
Hi,
We have already demos which you describes and its working fine. you can find code from below demo url:
https://vue3-datatable-document.vercel.app/alt-pagination

Check **Next Previous** demo from above url.
