### ISSUE TITLE
Sort problem

### ISSUE THREAD

**Issue by te-deum** [bhaveshpatel200/vue3-datatable#22]
Hello,

I am using this plugin and notice some problems on sorting.

Here is an example :
- Values : ['9320', '4110', '48BOX-K', '10009']
- Expected result : ["10009", "4110", "48BOX-K", "9320"]
- Result from plugin : ["48BOX-K", "4110", "9320", "10009"]

The problem come from the sort function inside _filteredRows_ function :
```javascript
        // sort rows
        var collator = new Intl.Collator(undefined, {
-->         numeric: true,
            sensitivity: 'base',
        });
        const sortOrder = currentSortDirection.value === 'desc' ? -1 : 1;

        rows.sort((a: any, b: any): number => {
            const valA = currentSortColumn.value?.split('.').reduce((obj: any, key: string) => obj?.[key], a);
            const valB = currentSortColumn.value?.split('.').reduce((obj: any, key: string) => obj?.[key], b);

            return collator.compare(valA, valB) * sortOrder;
        });
```
Option _numeric_ to true in _Intl.Collator_ options is the origin of the problem. Initialize this to false change the sort order to the expected result.
It may be better to set this option to true only when _column.type === 'number'_
```javascript
        // sort rows
        var collator = new Intl.Collator(undefined, {
            numeric: props.columns.find(col => col.field == currentSortColumn.value)?.type === 'number',
            sensitivity: 'base',
        });
```

Regards.

**Comment by bhaveshpatel200** [comment]
Hi te-deum,

Above issue has been solved in new version 1.1.4.
