### ISSUE TITLE
Custom pageSizeOptions to show ALL page

### ISSUE THREAD

**Issue by hgcassiopeia** [bhaveshpatel200/vue3-datatable#24]
Hello, how can I customize the 'pageSizeOptions' to display the option 'ALL' for the page size selection?

**Comment by bhaveshpatel200** [comment]
Hi,

We are not providing All page size option. but you can pass your custom array for page size in **pageSizeOptions** props where you can add your rows total length in this array and add that value in **pageSize** props.
