### ISSUE TITLE
Export Types

### ISSUE THREAD

**Issue by BayBreezy** [bhaveshpatel200/vue3-datatable#26]
Hello @bhaveshpatel200 ,

Thanks for the time taken to create this package.

I was wondering if is possible to cerate & export types for the package? That way we can get TS help when creating a column array etc...

**Comment by bhaveshpatel200** [comment]
Hi,

Sure i will check and update in next version if not.

**Comment by BayBreezy** [comment]
I would open a PR, but I am not sure how bundling works for vue packages. If I learn how, I will send a PR later today

**Comment by alexis-massa** [comment]
Hello, 
Reviving the conversation to add : In a properly configured IDE, it will mark import errors because of the type definitions not being resolved.

> Could not find a declaration file for module '@bhplugin/vue3-datatable'.
> ...
> The '@bhplugin/vue3-datatable' library may need to update its package.json or typings.

@BayBreezy You mentioned you were opening a PR for this, is it being worked on?

**Comment by BayBreezy** [comment]
@alexis-massa Sadly, I have not had the time to look into this.

**Comment by BayBreezy** [comment]
Hey @alexis-massa , I opened the PR for this just now.

@bhaveshpatel200 please take a look when you get the chance #33

**Comment by bhaveshpatel200** [comment]
Seems you have changed lots of code other than types related and also changed props name which will be break package for existing users.
as i have not deeply check fully code, so will check proper and test, once will get more time.

**Comment by BayBreezy** [comment]
Yeah... Check when you get the chance and let me know.
It was not a prop that was changed( so no breaking). I created a local variable to store the value of the prop. I saw where you were directly changing the value of the prop(which is bad practice)
