### ISSUE TITLE
Resolve error on dependency install with yarn

### ISSUE THREAD

**Issue by lucasboinet** [bhaveshpatel200/vue3-datatable#31]
Hello,

I have an issue while trying to use the `vue3-datatable` library. 

I followed the installations guide in the documentation but when it comes to import the datatable component and use it inside my vue3 app i encounter this error :

```
error  Resolve error: Cannot find module '/node_modules/@bhplugin/vue3-datatable/dist/vue3-datatable.umd.js'
    at createEsmNotFoundErr (node:internal/modules/cjs/loader:960:15)
    at finalizeEsmResolution (node:internal/modules/cjs/loader:953:15)
    at resolveExports (node:internal/modules/cjs/loader:482:14)
```

The error tell me that it is searching the `.umd.js` file right ? The problem is that i can't find this file inside the node_modules folder of this library.

I've tried to uninstall and reinstall the module, still the same.

Do you have any idea on how i can solve this issue ?

Thanks

_I hope i gave enough details, if not, dont hesitate to ask me more about it _

**Comment by bhaveshpatel200** [comment]
Hi,

I think can you please try below solution and let me know its works for you or not.

Try setting your "moduleResolution" strategy to "node" which isn't the default on "module": "umd".

check **moduleResolution** setting in tsconfig file.

**Comment by lucasboinet** [comment]
It was already set to 'node'. Can it be the node version of the project ? Its currently on 16.16

Or maybe the vue version ? Im not using the latest one of vue 3

**Comment by bhaveshpatel200** [comment]
Hi,

I am not sure about this package will work on vue 2.
Could you please provide zip of sample project so i can check.
