### ISSUE TITLE
error index

### ISSUE THREAD

**Issue by rizalda96** [bhaveshpatel200/vue3-datatable#32]
![image](https://github.com/bhaveshpatel200/vue3-datatable/assets/131124947/60e11247-3684-444c-b4ad-88146e863a0e)

error index on data.

key index always 0

**Comment by bhaveshpatel200** [comment]
Hi,

On which data you talk about this?

**Comment by rizalda96** [comment]
hi, thanks for response.

i mean, data from API

**Comment by rizalda96** [comment]
![image](https://github.com/bhaveshpatel200/vue3-datatable/assets/131124947/fdde77e2-3394-467a-9d5a-1899c1d26e23)

im using slot like this, and key always 0, not increase

**Comment by bhaveshpatel200** [comment]
I am only returning row object, so you can use your unique id here instead of key.

You can check documentations from the below link:
https://vue3-datatable-document.vercel.app/#slots

**Comment by faizaaulia** [comment]
hi @bhaveshpatel200 , what's the purpose of `key: 0` then? I'am also try to add a column for number that iterate the row number, with the data from API doesn't provide the sequential number, just a unique id
