### ISSUE TITLE
More slots

### ISSUE THREAD

**Issue by alexcroox** [bhaveshpatel200/vue3-datatable#35]
It would be great to expose more slots for custom styling. For example:

- filter button (so you can use different icons etc)
- filter input (so you can match the size of my custom button by using your own input component)
- pagination buttons

Thanks!

**Comment by bhaveshpatel200** [comment]
Hey,

All above you can achieve using to overwrite your custom css based on classes which is already given.

**Comment by alexcroox** [comment]
thanks, sometimes however when you are using a UI library it's not as simple as just applying classes, unless you seperately maintain all the classes the UI library applies internally to something like a button. Slots provide more flexibilty in this way. Would you accept a PR if I forked?
