### ISSUE TITLE
NuxtLink with target blank

### ISSUE THREAD

**Issue by Thav0** [bhaveshpatel200/vue3-datatable#38]
Hi,

When I try to use <NuxtLink> with target="_blank" the NuxtLink doesn't work

`
<vue3-datatable
                    :rows="salesReport"
                    :columns="cols"
                    :loading="loading"
                    :totalRows="paginationParams.totalItems"
                    :isServerMode="true"
                    :pageSize="paginationParams.perPage"
                    :pageSizeOptions="[50, 100, 200, 300]"
                    :currentPage="paginationParams.currentPage"
                    :columnFilter="true"
                    @change="updateSalesReportData"
                    class="text-xs"
                >
                    <template #id="data">
                        <div>
                            <NuxtLink class="text-blue-600 underline"
                                      :to="`/order/show/${data.value.id}`" target="_blank">
                                {{ data.value.id }}
                            </NuxtLink>
                        </div>
                    </template>
`
Only without target="_blank" works, but on this case I want to open a new tab.
The NuxtLink outside the vue3-datatable works with the target="_blank".
I think there is something wrong inside the component.

**Comment by bhaveshpatel200** [comment]
Ok, I will check and updates you.

**Comment by Thav0** [comment]
Any new about this issue?

**Comment by bhaveshpatel200** [comment]
Hi,
You can use @click.stop to prevent the parent click event, which will work. I will also update it in all our demos.

`<NuxtLink class="text-blue-600 underline" :to="'https://google.com'" target="_blank" @click.stop> Google.com </NuxtLink>`
