### ISSUE TITLE
Data not displayed with server mode

### ISSUE THREAD

**Issue by maha-oueghlani** [bhaveshpatel200/vue3-datatable#42]
Regarding the issue #28 about data not being displayed in the table in server mode, I want to reopen it to get more attention. When I fetch data with the Pinia store like this, it doesn't show data:

```
actions: {
      async fetchProducts(params) {
        return new Promise((resolve, reject) => {
          axios
            .get(`/api/products`, { params })
            .then((response) => {
              console.log(params);
              this.products = response.data.data;
              this.totalProducts = this.products.length;
              console.log(response)
              resolve(response.data);

            })
            .catch((err) => {
              reject(err);
            });
        });
        
```
        

and when I use this structure it works : 

```
 actions: {
      async fetchProducts(params) {
        return await axios
          .get(`/api/products`, { params })
          .then((response) => {
            this.products = response.data.data;
            this.totalProducts = this.products.length;
            console.log(response)
            return response

          })
          .catch((err) => {
            return err;
          });

      },
```

**BUT**   when I change to another page that contains a different datatable with a different store, it doesn't show data in the table.

I think it is an error of caching on the package or something like this

I would appreciate it if you could check this issue.

**Comment by bhaveshpatel200** [comment]
Hi,

This issue has been solved , so please check solution from the issue [#28](https://github.com/bhaveshpatel200/vue3-datatable/issues/28).
