### ISSUE TITLE
totalrows doesn't work

### ISSUE THREAD

**Issue by hungctdbk** [bhaveshpatel200/vue3-datatable#46]
Hello bhaveshpatel200
I'm having a problem when I want to display my data table with 300 rows. i use sql command to display the first 10 rows and update the totalRows value to 300. But it seems that the totalRows value is limited by the number of rows i upload from the database. Therefore, the page number only displays 1 instead of 30 pages.
Can you help me solve this problem?

**Comment by bhaveshpatel200** [comment]
Hi,

**totalrows** will be work with server side paginations.

You can check both server side pagination and client side pagination demo from the below links:
Client Side - https://vue3-datatable-document.vercel.app/static-mode
Server Side - https://vue3-datatable-document.vercel.app/basic

**Comment by cengizbarul** [comment]
Hello, I am having this problem, you can test the sample file.
Server Side - https://vue3-datatable-document.vercel.app/basic

**Comment by bhaveshpatel200** [comment]
Hi,
I’m not sure what issue you're experiencing, but all server-side demos are working correctly. No other users have reported this type of issue.

**Comment by cengizbarul** [comment]
Take a new vue project and create the demo, then send a request to your api and it still won't work.

**Comment by bhaveshpatel200** [comment]
Hi,

Could you please let me know what exactly error comes.
I will check and let you know if reproduce any error.

**Comment by bhaveshpatel200** [comment]
Hi,
I have checked with created newly Vue3 Vite project and it's working fine.

I think problem is that you have not updated live API URL instead of **'/api/user'**.
**https://vue3-datatable-document.vercel.app/api/user**
