### ISSUE TITLE
How to sticky LAST column?

### ISSUE THREAD

**Issue by KirePetrov** [bhaveshpatel200/vue3-datatable#49]
Hi there,

Is there a way to sticky the last column?

Usually on the last column is actions, and when table is too long, it's annoying to scroll all the way to the end.

BTW i have one issue or maybe its misunderstanding.
Example
`<vue3-datatable :sort-column="true" :column-filter="true" />`

In this case i think that the sort and filter should be enabled for all columns by default and i need to disable certains columns manually.

But its NOT, i have to put `'sort' => true, 'filter' => true` on each column to actually show the sort and filter.

**Comment by bhaveshpatel200** [comment]
Hi KirePetrov,

- We have not any option for last column sticky but it will be possible with css.

- We have option in column option for disable sort and filter for specific column.

**Comment by KirePetrov** [comment]
> Hi KirePetrov,
> 
>     * We have not any option for last column sticky but it will be possible with css.
> 
>     * We have option in column option for disable sort and filter for specific column.

can you explain how to do sticky last column with CSS and this column has slotMode also?
