### ISSUE TITLE
Regular links don't work as expected

### ISSUE THREAD

**Issue by sandor-si** [bhaveshpatel200/vue3-datatable#54]
Look at the advanced example's email column for instance
https://vue3-datatable-document.vercel.app/advanced

When you click on it it would normally open up the default mail application.

I think the bug is caused by using **prevent** modifier.

**Comment by bhaveshpatel200** [comment]
Hi,
You can use @click.stop to prevent the parent click event, which will work. I will also update it in all our demos.

`<template #email="data">
                <a :href="`mailto:${data.value.email}`" class="text-primary hover:underline" @click.stop>{{ data.value.email }}</a>
            </template>`
