### ISSUE TITLE
Total rows not working

### ISSUE THREAD

**Issue by HuaMiaoyi** [bhaveshpatel200/vue3-datatable#7]
totalRows is invalid when isServerMode is true，my items length is 10 total_rows is 11 but the page displays only 1 page of 10 data
`<vue3-datatable 
                    :rows="items" 
                    :columns="cols" 
                    :loading="loading" 
                    :isServerMode="true"
                    :totalRows="total_rows" 
                    :hasCheckbox="true" 
                    :sortable="true" 
                    sortColumn="createTime"
                    sortDirection="desc" 
                    :search="search" 
                    :page="data.page" 
                    :pageSize="data.limit"
                    @pageChange="changeServer" noDataContent="没有符合条件的数据" skin="whitespace-nowrap table-hover"
                    @pageSizeChange="changePageSize" paginationInfo="显示 {0} 至 {1} 共 {2} 条数据"
                </vue3-datatable>`

**Comment by bhaveshpatel200** [comment]
Hi @HuaMiaoyi,

Please make sure you are using latest version of this package.

**Comment by HuaMiaoyi** [comment]
hi
Thank you for your reply. I took a look at the version of the project. It is indeed because my version is too low.
my current version is **1.0.1**
the minimum version required for server paging is **1.1.0**
