### ISSUE TITLE
Key for sequential numbers

### ISSUE THREAD

**Issue by prasetyo-jeanu** [bhaveshpatel200/vue3-datatable#8]
Can you generate keys with sequential numbers rather than just zeros? So as to create a number sequence in the table.

```
<template #number="data">
     <strong>{{ data.key + 1 }}</strong>
</template>
```

**Comment by bhaveshpatel200** [comment]
Hi,

It's  upto you to how to display sequential numbers. so my suggestions is that you can add one id columns which incremental number and display that as sequential numbers which is best ways.

you can check our demos.
https://vue3-datatable-document.vercel.app/advanced
https://github.com/bhaveshpatel200/vue3-datatable-document/blob/main/pages/advanced.vue

**Comment by prasetyo-jeanu** [comment]
I think it's better to generate from the frontend than from the backend especially from the database.
imagine an autoincrement id database where **one row is deleted**, or using uuid

**Comment by bhaveshpatel200** [comment]
If you are not passing any unique id column then we are taking row index as key for this table and managed.
For this time i am thinking that this features is needed, so will think about this in future.

**Comment by prasetyo-jeanu** [comment]
well, I'll wait pleasantly for this sequence number feature

**Comment by faizaaulia** [comment]
> If you are not passing any unique id column then we are taking row index as key for this table and managed. For this time i am thinking that this features is needed, so will think about this in future.

hi @bhaveshpatel200 , which one do you mean by "taking row index as key"? is it this key? but the value of the key is 0 for all rows
![image](https://github.com/user-attachments/assets/48c37af9-3359-4913-91ec-38147d683b7c)
![image](https://github.com/user-attachments/assets/7c3bbe5a-9de4-4e35-890c-9b66370296f7)

**Comment by bhaveshpatel200** [comment]
Currently i think i am not providing to return row index. if you want that then add row index from your data and use that key in template which will works for you.
